-- PostgreSQL建表语句
CREATE TABLE ods.cost_mapping_aggregation(
         id SERIAL PRIMARY KEY,
         hos_code VARCHAR(255),
         hos_name VARCHAR(255),
         hos_project_code VARCHAR(255),
         hos_project_name VARCHAR(255),
         charge_type_code_hs VARCHAR(255),
         charge_type_name_hs VARCHAR(255),
         ins_city_project_code VARCHAR(255),
         ins_city_project_name VARCHAR(255),
         ins_pro_project_code VARCHAR(255),
         ins_pro_project_name VARCHAR(255),
         mija_project_code VARCHAR(255),
         mija_project_name VARCHAR(255),
         mija_medicine_generic_code VARCHAR(255),
         mija_medicine_generic_name VARCHAR(255),
         mija_medicine_dosage_code VARCHAR(255),
         mija_medicine_dosage_name VARCHAR(255),
         mija_medicine_spec_code VARCHAR(255),
         mija_medicine_spec_name VARCHAR(255),
         mija_medicine_package_code VARCHAR(255),
         mija_medicine_package_name VARCHAR(255),
         mija_medicine_company_code VARCHAR(255),
         mija_medicine_company_name VARCHAR(255),
         ins_nation_project_code VARCHAR(255),
         ins_nation_project_name VARCHAR(255),
         mapping_mode VARCHAR(255),
         mapping_prob double precision,
         mapping_date VARCHAR(255),
         mija_database_version VARCHAR(255),
         fee_dictionary_version VARCHAR(255),
         data_source VARCHAR(255),
         insurance_code VARCHAR(255),
         org_code VARCHAR(255),
         org_name VARCHAR(255),
         big_class_name VARCHAR(255),
         big_class_map_prob double precision,
         big_class_map_mode VARCHAR(255),
         big_class_preprocess_name VARCHAR(255),
         single_module_preprocess_name VARCHAR(255),
         es_keyword VARCHAR(255),
         frequency double precision,
         fee_standardize_version VARCHAR(255),
         insurance_name VARCHAR(255),
         batch_id VARCHAR(255),
         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PostgreSQL建表语句
CREATE TABLE group_param (
                 id SERIAL PRIMARY KEY,
                 pid VARCHAR(255),
                 zdcode VARCHAR(255),
                 sscode VARCHAR(255),
                 age double precision,
                 czdcode VARCHAR(255),
                 csscode VARCHAR(255),
                 daynum double precision,
                 sex VARCHAR(255),
                 xsetz double precision,
                 lyfs double precision,
                 py_group_param JSONB,
                 settle_date varchar(255),
                 source_flag INTEGER,
                 IRPDID VARCHAR(255),
                 hos_code VARCHAR(255),
                 batch_id VARCHAR(255),
                 fee_list JSONB,
                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PostgreSQL建表语句
CREATE TABLE cost_detail (
               id SERIAL PRIMARY KEY,
               pid VARCHAR(255),
               mapping_mark VARCHAR(255),
               item_code VARCHAR(255),
               item_name VARCHAR(255),
               charge_type VARCHAR(255),
               charge_type_name VARCHAR(255),
               insurance_code VARCHAR(255),
               insurance_name VARCHAR(255),
               cost_code_chs VARCHAR(255),
               cost_name_chs VARCHAR(255),
               cost_code_mija VARCHAR(255),
               cost_name_mija VARCHAR(255),
               org_code VARCHAR(255),
               cost_amount double precision,
               cost_fee double precision,
               batch_id VARCHAR(255),
               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 全部字段名称（小写）
-- PostgreSQL建表语句
CREATE TABLE bill_basic_info (
            id SERIAL PRIMARY KEY,
            pid VARCHAR(255),
            qdlsh VARCHAR(255),
            ddyljgmc VARCHAR(255),
            ddyljgdm VARCHAR(255),
            ybjsdj VARCHAR(255),
            ybbh VARCHAR(255),
            bah VARCHAR(255),
            sbsj VARCHAR(255),
            xm VARCHAR(255),
            xb VARCHAR(255),
            xbmc VARCHAR(255),
            csrq VARCHAR(255),
            nl REAL,
            gj VARCHAR(255),
            gjmc VARCHAR(255),
            bzyzsnl REAL,
            xsenl REAL,
            mz VARCHAR(255),
            mzdm VARCHAR(255),
            mzmc VARCHAR(255),
            hzzjlb VARCHAR(255),
            hzzjhm VARCHAR(255),
            zy VARCHAR(255),
            zydm VARCHAR(255),
            zymc VARCHAR(255),
            xzz VARCHAR(255),
            jzdzmc_sheng VARCHAR(255),
            jzdzmc_shi VARCHAR(255),
            jzdzmc_xian VARCHAR(255),
            jzdz_mph VARCHAR(255),
            jzdz_sheng VARCHAR(255),
            jzdz_shi VARCHAR(255),
            jzdz_xian VARCHAR(255),
            gzdwdz VARCHAR(255),
            gzdwjdz VARCHAR(255),
            gzdwmc VARCHAR(255),
            dwdh VARCHAR(255),
            yb VARCHAR(255),
            yb3 VARCHAR(255),
            lxrxm VARCHAR(255),
            gx VARCHAR(255),
            gxmc VARCHAR(255),
            dz VARCHAR(255),
            lxdzmc_sheng VARCHAR(255),
            lxdzmc_shi VARCHAR(255),
            lxdzmc_xian VARCHAR(255),
            lxdz_sheng VARCHAR(255),
            lxdz_shi VARCHAR(255),
            lxdz_xian VARCHAR(255),
            lxdz_xxdz VARCHAR(255),
            dh2 VARCHAR(255),
            yblx VARCHAR(255),
            tsrylx VARCHAR(255),
            cbd VARCHAR(255),
            sserylxxmc VARCHAR(255),
            xsecstz REAL,
            dxsecstz VARCHAR(255),
            xserytz REAL,
            dxserytz VARCHAR(255),
            mt_jzrq VARCHAR(255),
            mt_zdkb VARCHAR(255),
            mt_zdkbmc VARCHAR(255),
            cyjbdm_zb VARCHAR(255),
            cyjbdm_zz VARCHAR(255),
            outDiagnosisOpsDtoList VARCHAR(512),
            outSurgeryOpsDtoList VARCHAR(512),
            zyyllx VARCHAR(255),
            zyyllxmc VARCHAR(255),
            rytj VARCHAR(255),
            rytjmc VARCHAR(255),
            zllx VARCHAR(255),
            zllxmc VARCHAR(255),
            rysj VARCHAR(255),
            rysjs VARCHAR(255),
            rykb VARCHAR(255),
            rykbmc VARCHAR(255),
            zkkb VARCHAR(255),
            zkkbmc VARCHAR(255),
            cykb VARCHAR(255),
            cykbmc VARCHAR(255),
            cysj VARCHAR(255),
            cysjs VARCHAR(255),
            sjzyts REAL,
            jbbm_xy VARCHAR(255),
            mzzd_xy VARCHAR(255),
            jbbm_zy VARCHAR(255),
            mzzd_zy VARCHAR(255),
            zddmjs VARCHAR(255),
            ssjczdmjs VARCHAR(255),
            cyzyzd_zb VARCHAR(255),
            cyzyzd_zz VARCHAR(255),
            rybq_zyzb VARCHAR(255),
            rybq_zyzz VARCHAR(255),
            hxjsy_fz REAL,
            hxjsy_ts REAL,
            hxjsy_xs REAL,
            ryh_f REAL,
            ryh_t REAL,
            ryh_xs REAL,
            ryq_f REAL,
            ryq_t REAL,
            ryq_xs REAL,
            intensiveCareDtoList VARCHAR(512),
            bloodTransfusionList VARCHAR(512),
            vetime VARCHAR(255),
            icu VARCHAR(255),
            stllf VARCHAR(255),
            batch_id VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 全部字段名称（小写）
-- PostgreSQL建表语句
CREATE TABLE patient_basic_info (
             id SERIAL PRIMARY KEY,
             pid VARCHAR(255),
             usercode VARCHAR(255),
             username VARCHAR(255),
             ylfkfs VARCHAR(255),
             jkkh VARCHAR(255),
             zycs VARCHAR(255),
             bah VARCHAR(255),
             xm VARCHAR(255),
             xb VARCHAR(255),
             xbmc VARCHAR(255),
             csrq VARCHAR(255),
             nl REAL,
             gj VARCHAR(255),
             gjmc VARCHAR(255),
             bzyzsnl REAL,
             xsenl REAL,
             xsecstz REAL,
             dxsecstz VARCHAR(255),
             xserytz REAL,
             dxserytz VARCHAR(255),
             csd VARCHAR(255),
             gg VARCHAR(255),
             mz VARCHAR(255),
             mzdm VARCHAR(255),
             mzmc VARCHAR(255),
             sfzh VARCHAR(255),
             zy VARCHAR(255),
             zydm VARCHAR(255),
             zymc VARCHAR(255),
             hy VARCHAR(255),
             jzdzmc_sheng VARCHAR(255),
             jzdzmc_shi VARCHAR(255),
             jzdzmc_xian VARCHAR(255),
             jzdz_mph VARCHAR(255),
             jzdz_sheng VARCHAR(255),
             jzdz_shi VARCHAR(255),
             jzdz_xian VARCHAR(255),
             dh VARCHAR(255),
             xzz VARCHAR(255),
             yb1 VARCHAR(255),
             hkdz VARCHAR(255),
             yb2 VARCHAR(255),
             gzdwdz VARCHAR(255),
             gzdwjdz VARCHAR(255),
             gzdwmc VARCHAR(255),
             dwdh VARCHAR(255),
             yb VARCHAR(255),
             yb3 VARCHAR(255),
             lxrxm VARCHAR(255),
             gx VARCHAR(255),
             gxmc VARCHAR(255),
             dz VARCHAR(255),
             lxdzmc_sheng VARCHAR(255),
             lxdzmc_shi VARCHAR(255),
             lxdzmc_xian VARCHAR(255),
             lxdz_sheng VARCHAR(255),
             lxdz_shi VARCHAR(255),
             lxdz_xian VARCHAR(255),
             lxdz_xxdz VARCHAR(255),
             dh2 VARCHAR(255),
             rytj VARCHAR(255),
             rytjmc VARCHAR(255),
             rysj VARCHAR(255),
             rysjs VARCHAR(255),
             rykb VARCHAR(255),
             rykbmc VARCHAR(255),
             rybf VARCHAR(255),
             zkkb VARCHAR(255),
             zkkbmc VARCHAR(255),
             cysj VARCHAR(255),
             cysjs VARCHAR(255),
             cykb VARCHAR(255),
             cykbmc VARCHAR(255),
             cybf VARCHAR(255),
             sjzyts REAL,
             jbbm_xy VARCHAR(255),
             mzzd_xy VARCHAR(255),
             sunshangzdlist JSONB,
             binglidiagnosislist JSONB,
             ywgm VARCHAR(255),
             gmyw VARCHAR(255),
             swhzsj VARCHAR(255),
             xx VARCHAR(255),
             rh VARCHAR(255),
             kzr VARCHAR(255),
             zrys VARCHAR(255),
             zzys VARCHAR(255),
             zzysmc VARCHAR(255),
             zyys VARCHAR(255),
             zrhs VARCHAR(255),
             zrhsmc VARCHAR(255),
             jxys VARCHAR(255),
             sxys VARCHAR(255),
             bmy VARCHAR(255),
             bazl VARCHAR(255),
             zkys VARCHAR(255),
             zkhs VARCHAR(255),
             zkrq VARCHAR(255),
             lyfs VARCHAR(255),
             lyfsmc VARCHAR(255),
             yzzy_jgdm VARCHAR(255),
             yzzy_jgmc VARCHAR(255),
             yzzy_yljg VARCHAR(255),
             wsy_yljg VARCHAR(255),
             sfzzyjh VARCHAR(255),
             sfzzyjhmc VARCHAR(255),
             md VARCHAR(255),
             ryh_f REAL,
             ryh_t REAL,
             ryh_xs REAL,
             ryq_f REAL,
             ryq_t REAL,
             ryq_xs REAL,
             zfy REAL,
             zfje REAL,
             ylfuf REAL,
             zlczf REAL,
             hlf REAL,
             qtfy REAL,
             blzdf REAL,
             syszdf REAL,
             yxxzdf REAL,
             lczdxmf REAL,
             fsszlxmf REAL,
             wlzlf REAL,
             sszlf REAL,
             maf REAL,
             ssf REAL,
             kff REAL,
             zyzlf REAL,
             xyf REAL,
             kjywf REAL,
             zcyf REAL,
             zcyf1 REAL,
             xf REAL,
             bdblzpf REAL,
             qdblzpf REAL,
             nxyzlzpf REAL,
             xbyzlzpf REAL,
             hcyyclf REAL,
             yyclf REAL,
             ycxyyclf REAL,
             qtf REAL,
             zyqtf REAL,
             dbzgl VARCHAR(255),
             lcljgl VARCHAR(255),
             zdfhqk VARCHAR(255),
             mcfhbz VARCHAR(255),
             mcfhbzmc VARCHAR(255),
             rcfhbz VARCHAR(255),
             rcfhbzmc VARCHAR(255),
             sqysh VARCHAR(255),
             sqyshmc VARCHAR(255),
             lcycl VARCHAR(255),
             lcyclmc VARCHAR(255),
             fsybl VARCHAR(255),
             fsyblmc VARCHAR(255),
             qjqk VARCHAR(255),
             cgcs REAL,
             qjcs REAL,
             zgqk VARCHAR(255),
             vetime VARCHAR(255),
             icu VARCHAR(255),
             stllf VARCHAR(255),
            batch_id VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -- 全部字段名称（小写）
--
-- CREATE TABLE bill_diagnosis_surgery_info (
--     id SERIAL PRIMARY KEY,
--     diagnosisList text,
--     surgeryList text,
--     batch_id VARCHAR(255),
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- CREATE TABLE patient_diagnosis_surgery_info (
--      id SERIAL PRIMARY KEY,
--      diagnosisList text,
--      surgeryList text,
--      batch_id VARCHAR(255),
--      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );


     
     
     