# 数据库配置
db.url=jdbc:postgresql://adb.mijahealth.com:15432/warehouse?currentSchema=ods&stringtype=unspecified&reWriteBatchedInserts=true&batchMode=extended
db.user=sa
db.password=0yV2V4Gepsao
db.batchSize=1000

