tables:
  - name: group_param_mrhp
    description: "质控分组参数"
    columns:
      - name: pid
      - name: zdcode
      - name: sscode
      - name: age
      - name: czdcode
      - name: csscode
      - name: daynum
      - name: sex
      - name: xsetz
      - name: lyfs
      - name: source_flag
      - name: py_group_param
      - name: settle_date
      - name: iprdid
      - name: hos_code
      - name: batch_id
      - name: batch_name
  - name: group_param
    description: "质控分组参数"
    columns:
      - name: pid
      - name: zdcode
      - name: sscode
      - name: age
      - name: czdcode
      - name: csscode
      - name: daynum
      - name: sex
      - name: xsetz
      - name: lyfs
      - name: source_flag
      - name: py_group_param
      - name: settle_date
      - name: iprdid
      - name: hos_code
      - name: batch_id
      - name: batch_name

  - name: cost_mapping_aggregation
    description: "费用映射聚合表"
    columns:
      - name: hos_code
      - name: hos_name
      - name: hos_project_code
      - name: hos_project_name
      - name: charge_type_code_hs
      - name: charge_type_name_hs
      - name: ins_city_project_code
      - name: ins_city_project_name
      - name: ins_pro_project_code
      - name: ins_pro_project_name
      - name: mija_project_code
      - name: mija_project_name
      - name: mija_medicine_generic_code
      - name: mija_medicine_generic_name
      - name: mija_medicine_dosage_code
      - name: mija_medicine_dosage_name
      - name: mija_medicine_spec_code
      - name: mija_medicine_spec_name
      - name: mija_medicine_package_code
      - name: mija_medicine_package_name
      - name: mija_medicine_company_code
      - name: mija_medicine_company_name
      - name: ins_nation_project_code
      - name: ins_nation_project_name
      - name: mapping_mode
      - name: mapping_prob
      - name: mapping_date
      - name: mija_database_version
      - name: fee_dictionary_version
      - name: data_source
      - name: insurance_code
      - name: org_code
      - name: org_name
      - name: big_class_name
      - name: big_class_map_prob
      - name: big_class_map_mode
      - name: big_class_preprocess_name
      - name: single_module_preprocess_name
      - name: es_keyword
      - name: frequency
      - name: fee_standardize_version
      - name: insurance_name
      - name: batch_id
      - name: batch_name
  - name: cost_mapping_aggregation_mrhp
    description: "质控费用映射聚合表"
    columns:
      - name: hos_code
      - name: hos_name
      - name: hos_project_code
      - name: hos_project_name
      - name: charge_type_code_hs
      - name: charge_type_name_hs
      - name: ins_city_project_code
      - name: ins_city_project_name
      - name: ins_pro_project_code
      - name: ins_pro_project_name
      - name: mija_project_code
      - name: mija_project_name
      - name: mija_medicine_generic_code
      - name: mija_medicine_generic_name
      - name: mija_medicine_dosage_code
      - name: mija_medicine_dosage_name
      - name: mija_medicine_spec_code
      - name: mija_medicine_spec_name
      - name: mija_medicine_package_code
      - name: mija_medicine_package_name
      - name: mija_medicine_company_code
      - name: mija_medicine_company_name
      - name: ins_nation_project_code
      - name: ins_nation_project_name
      - name: mapping_mode
      - name: mapping_prob
      - name: mapping_date
      - name: mija_database_version
      - name: fee_dictionary_version
      - name: data_source
      - name: insurance_code
      - name: org_code
      - name: org_name
      - name: big_class_name
      - name: big_class_map_prob
      - name: big_class_map_mode
      - name: big_class_preprocess_name
      - name: single_module_preprocess_name
      - name: es_keyword
      - name: frequency
      - name: fee_standardize_version
      - name: insurance_name
      - name: batch_id
      - name: batch_name
  - name: cost_detail_mrhp
    description: "质控费用明细"
    columns:
      - name: pid
      - name: mapping_mark
      - name: feecode
      - name: feename
      - name: itemclasscode
      - name: charge_type_name_hs
      - name: medicalInsurancecode
      - name: insurance_name
      - name: ins_nation_project_code
      - name: ins_nation_project_name
      - name: mija_project_code
      - name: mija_project_name
      - name: orgcode
      - name: number
      - name: fee
      - name: source_flag
      - name: created_at
      - name: batch_name
      - name: batch_id

  - name: cost_detail
    description: "费用明细"
    columns:
      - name: pid
      - name: mapping_mark
      - name: feecode
      - name: feename
      - name: itemclasscode
      - name: charge_type_name_hs
      - name: medicalInsurancecode
      - name: insurance_name
      - name: ins_nation_project_code
      - name: ins_nation_project_name
      - name: mija_project_code
      - name: mija_project_name
      - name: orgcode
      - name: number
      - name: fee
      - name: source_flag
      - name: created_at
      - name: batch_name
      - name: batch_id




